import type { GenerationTask } from "./types";
import { assetPath } from "../../lib/assetPath";

/**
 * 原型首次打开时展示的演示历史。
 *
 * 这里全部使用虚构数据，避免把真实用户的手机号、余额或私有图片带入原型。
 */
export const DEMO_TASKS: GenerationTask[] = [
  {
    id: "demo-mug-main",
    mode: "text-to-image",
    imageType: "main",
    prompt: "马克杯",
    model: "Ptu1.0",
    aspectRatio: "1:1",
    quantity: 1,
    sourceImages: [],
    modelImages: [],
    garmentImages: [],
    resultImages: [assetPath("demo/mug-hero.svg")],
    status: "completed",
    createdAt: "2026-07-08T17:24:47+08:00",
  },
  {
    id: "demo-mug-set",
    mode: "text-to-image",
    imageType: "set",
    prompt: "马克杯",
    model: "Ptu1.0",
    aspectRatio: "1:1",
    quantity: 1,
    sourceImages: [],
    modelImages: [],
    garmentImages: [],
    resultImages: [
      assetPath("demo/mug-hero.svg"),
      assetPath("demo/bowl-detail.svg"),
      assetPath("demo/bowl-scene.svg"),
      assetPath("demo/mug-hero.svg"),
      assetPath("demo/bowl-detail.svg"),
      assetPath("demo/bowl-scene.svg"),
    ],
    status: "completed",
    createdAt: "2026-07-08T17:24:54+08:00",
  },
  {
    id: "demo-mug-listing",
    mode: "text-to-image",
    imageType: "listing",
    prompt: "马克杯，材质与工艺详情展示",
    model: "Ptu1.0",
    aspectRatio: "1:1",
    quantity: 1,
    sourceImages: [],
    modelImages: [],
    garmentImages: [],
    resultImages: [
      assetPath("demo/mug-hero.svg"),
      assetPath("demo/bowl-detail.svg"),
      assetPath("demo/bowl-scene.svg"),
      assetPath("demo/mug-hero.svg"),
      assetPath("demo/bowl-detail.svg"),
    ],
    status: "completed",
    createdAt: "2026-07-08T17:25:00+08:00",
  },
  {
    id: "demo-mug-poster",
    mode: "text-to-image",
    imageType: "poster",
    prompt: "马克杯，柔和晨光，高级电商海报",
    model: "Ptu1.0",
    aspectRatio: "1:1",
    quantity: 1,
    sourceImages: [],
    modelImages: [],
    garmentImages: [],
    resultImages: [assetPath("demo/mug-hero.svg")],
    status: "completed",
    createdAt: "2026-07-08T17:25:05+08:00",
  },
  {
    id: "demo-bowl-set",
    mode: "image-to-image",
    imageType: "set",
    prompt: "猫碗，套图，保留产品结构并优化商业布光",
    model: "Ptu1.0",
    aspectRatio: "1:1",
    quantity: 3,
    sourceImages: [assetPath("demo/bowl-source.svg")],
    modelImages: [],
    garmentImages: [],
    resultImages: [
      assetPath("demo/bowl-hero.svg"),
      assetPath("demo/bowl-detail.svg"),
      assetPath("demo/bowl-scene.svg"),
    ],
    status: "completed",
    createdAt: "2026-06-28T19:24:09+08:00",
  },
  {
    id: "demo-cutout",
    mode: "ai-retouch",
    imageType: "main",
    retouchMode: "cutout",
    prompt: "将猫抠出来",
    model: "Ptu1.0",
    aspectRatio: "1:1",
    quantity: 1,
    sourceImages: [assetPath("demo/cat-source.svg")],
    modelImages: [],
    garmentImages: [],
    resultImages: [assetPath("demo/cat-cutout.svg")],
    status: "completed",
    createdAt: "2026-05-11T10:26:45+08:00",
  },
];
